WebAssignment/Models/Login.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Login
    {
        public int UserID { get; set; }

        [Display(Name = "E-mail")]
        public string UserEmail { get; set; }

        [Display(Name = "Password")]

        [DataType(DataType.Password)]
        public string UserPassword { get; set; }
        public int UserType { get; set; }
    }
}

WebAssignment/Controllers/LoginsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAssignment.Models;

namespace WebAssignment.Controllers
{
    public class LoginsController : Controller
    {

        private Assignment_2_CSI2441Entities1 db = new Assignment_2_CSI2441Entities1();

        // GET: Logins
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(WebAssignment.Models.Login userModel, FormCollection Form)
        {

                var userLogin = db.Logins.Where(login => login.UserEmail == userModel.UserEmail && login.UserPassword == userModel.UserPassword).FirstOrDefault();

                if (userLogin == null)
                {
                    
                    return View("Index", userModel);
                }
                else
                {

                    Session["sessionID"] = userLogin.UserID.ToString();

    
                    if (userLogin.UserType == 1)
                    {
                        return RedirectToAction("Options", "Unit_Enrolment");
                    
                    }
                    else
                    {
                        return RedirectToAction("Options", "Units");
                    }
                }
            }

        }


    }

WebAssignment/Views/Logins/Index.cshtml
@model WebAssignment.Models.Login

@{
    ViewBag.Title = "Log-in";
}

<h2>Login</h2>



<div id="login_div">

    @using (Html.BeginForm("Login", "Logins", FormMethod.Post))
    {
        <center>
            <table>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.UserEmail)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.UserEmail)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.UserPassword)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.UserPassword)
                    </td>
                </tr>

                <tr>
                    <td>&nbsp;</td>
                    <td>
                        <input type="submit" name="" value="Login" />
                        
                    </td>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </center>
    }
</div>

WebAssignment/Views/Logins/Login.cshtml
@model WebAssignment.Models.Login

@{
    ViewBag.Title = "Log-in";
}

<h2>Login</h2>



<div id="login_div">

    @using (Html.BeginForm("Login", "Login", FormMethod.Post))
    {
        <center>
            <table>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.UserEmail)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.UserEmail)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.UserPassword)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.UserPassword)
                    </td>
                </tr>
                
                <tr>
                    <td>
                        <input type="submit" name="" value="Login" />
  
                    </td>
                </tr>
            </table>
        </center>
    }
</div>