WebAssignment/Models/Unit.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit()
        {
            this.Unit_Enrolment = new HashSet<Unit_Enrolment>();
        }

        [Display(Name = "Unit Code")]
        [Required(ErrorMessage = "Unitcode cannot be empty!")]
        [RegularExpression(@"^[A-Za-z]{3}\d{4}$", ErrorMessage = "Unitcode doesn't match the required format! (Format: AAA-1111)")]
        public string UnitCode { get; set; }

        [Display(Name = "Unit Title")]
        [Required(ErrorMessage = "Unit Title cannot be empty!")]
        public string UnitTitle { get; set; }

        [Display(Name = "Unit Coordinator")]
        public string UnitCoordinator { get; set; }

        [Display(Name = "Unit Outline")]
        public string UnitOuttlinePdf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit_Enrolment> Unit_Enrolment { get; set; }
    }
}

WebAssignment/Controllers/UnitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAssignment.Models;

namespace WebAssignment.Controllers
{
    public class UnitsController : Controller
    {
        private Assignment_2_CSI2441Entities1 db = new Assignment_2_CSI2441Entities1();

        public ActionResult Options()
        {
            if (Session["sessionID"] == null || Session["sessionID"].ToString() != "1")
            {
                return RedirectToAction("Index", "Logins");
            }
            return View();
        }

        // GET: Units
        public ActionResult Index()
        {
            if (Session["sessionID"] == null || Session["sessionID"].ToString() != "1")
            {
                return RedirectToAction("Index", "Logins");
            }

            return View(db.Units.ToList());
        }

        // GET: Units/Details/5
        public ActionResult Details(string id)
        {
            if (Session["sessionID"] == null || Session["sessionID"].ToString() != "1")
            {
                return RedirectToAction("Index", "Logins");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Unit unit = db.Units.Find(id);
            if (unit == null)
            {
                return HttpNotFound();
            }
            return View(unit);
        }

        // GET: Units/Create
        public ActionResult Create()
        {
            if (Session["sessionID"] == null || Session["sessionID"].ToString() != "1")
            {
                return RedirectToAction("Index", "Logins");
            }

            return View();
        }

        // POST: Units/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UnitCode,UnitTitle,UnitCoordinator,UnitOuttlinePdf")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                db.Units.Add(unit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(unit);
        }

        // GET: Units/Edit/5
        public ActionResult Edit(string id)
        {
            if (Session["sessionID"] == null || Session["sessionID"].ToString() != "1")
            {
                return RedirectToAction("Index", "Logins");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Unit unit = db.Units.Find(id);
            if (unit == null)
            {
                return HttpNotFound();
            }
            return View(unit);
        }

        // POST: Units/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UnitCode,UnitTitle,UnitCoordinator,UnitOuttlinePdf")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(unit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(unit);
        }

        // GET: Units/Delete/5
        public ActionResult Delete(string id)
        {
            if (Session["sessionID"] == null || Session["sessionID"].ToString() != "1")
            {
                return RedirectToAction("Index", "Logins");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Unit unit = db.Units.Find(id);
            if (unit == null)
            {
                return HttpNotFound();
            }
            return View(unit);
        }

        // POST: Units/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Unit unit = db.Units.Find(id);
            db.Units.Remove(unit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebAssignment/Views/Units/Create.cshtml
@model WebAssignment.Models.Unit

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Units", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Unit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UnitCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitCoordinator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitCoordinator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitCoordinator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitOuttlinePdf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitOuttlinePdf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitOuttlinePdf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAssignment/Views/Units/Delete.cshtml
@model WebAssignment.Models.Unit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Unit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UnitTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitCoordinator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitCoordinator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitOuttlinePdf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitOuttlinePdf)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebAssignment/Views/Units/Details.cshtml
@model WebAssignment.Models.Unit

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Unit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UnitTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitCoordinator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitCoordinator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitOuttlinePdf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitOuttlinePdf)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UnitCode }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebAssignment/Views/Units/Edit.cshtml
@model WebAssignment.Models.Unit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Unit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UnitCode)

        <div class="form-group">
            @Html.LabelFor(model => model.UnitTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitCoordinator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitCoordinator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitCoordinator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitOuttlinePdf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitOuttlinePdf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitOuttlinePdf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAssignment/Views/Units/Index.cshtml
@model IEnumerable<WebAssignment.Models.Unit>

@{
    ViewBag.Title = "Index";
}

<h2>Manage Units</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UnitTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitCoordinator)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitOuttlinePdf)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UnitTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitCoordinator)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitOuttlinePdf)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UnitCode }) |
            @Html.ActionLink("Details", "Details", new { id=item.UnitCode }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UnitCode })
        </td>
    </tr>
}

</table>

WebAssignment/Views/Units/Options.cshtml
<h2>Search Criteria</h2>

<div style="align-content:center">
    <table align="center">
        <tr>
            <td><a class="btn btn-success btn-group-sm" href="~/Units/Index">Manage Units</a> </td>
            <td>&nbsp;</td>
            <td><a class="btn btn-success btn-sm" href="~/Students/Index">Manage Students</a> </td>
        </tr>
    </table>
</div>